### ISSUE TITLE
Create the Initial Microservice Skeleton

### ISSUE THREAD

**Issue by VickyZauner** [DevOps-Recommendations-Squad/recommendations#3]
**As a** developer
**I need** basic code
**So that** I can expand and build on the functionality

### Details & Assumptions: 
* We are using python with flask
* The port we are using is 8000
* It should also setup a testing environment as well

### Acceptance Criteria:

```gherkin
Given there is a skeleton app
When I run a "git clone" on the project
Then I should get a minimal Flask application with Honcho setup
When I run "honcho start"
Then I should have a Flask server running at "localhost:8000"
```

**Comment by Some1Somewhere** [comment]
![image](https://user-images.githubusercontent.com/23713668/196011265-6130a52f-7e7d-4b2e-b188-10daa3fcab8e.png)
